[general]
import = [ "/home/gustavo/.config/omarchy/current/theme/alacritty.toml" ]
working_directory = "/home/gustavo/Desktop/dev"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },

  # --- Ctrl+C = Copy ---
  { key = "C", mods = "Control", action = "Copy" },

  # --- Ctrl+V = Paste ---
  { key = "V", mods = "Control", action = "Paste" },

  # --- Keep SIGINT (^C) on Ctrl+Shift+C ---
  { key = "C", mods = "Control|Shift", chars = "\u0003" }
]
